### ISSUE TITLE
Link Not Working

### ISSUE THREAD

**Issue by eddiejaoude** [empowerhack/Hababy-Website#5]
@ahenkels ...

> The link to HaBaby (http://hababy.empowerhack.io/index.html) doesn't work

**Comment by tanyapowell** [comment]
@empowerhack/hababy think this repo needs a `gh-pages` branch (with everything you currently have on the `master` branch) for the link to work

**Comment by eddiejaoude** [comment]
@tanyapowell there is some PHP in the site for a contact page. If we could remove this then yes it could be a **GitHub Pages** site

**Comment by eddiejaoude** [comment]
@ahenkels what do you think of above?

**Comment by ahenkels** [comment]
Sounds good!

**Comment by ahenkels** [comment]
Hi @eddiejaoude @tanyapowell are you able to please move this to a github pages site?

**Comment by tanyapowell** [comment]
@ahenkels who is maintaining this website? Until the contact page has been updated so it no longer uses PHP it won't work on github pages

**Comment by ahenkels** [comment]
Hi @tanyapowell no one is maintaining it - that's why I'm asking for help :) It's fine with me to take the contact form out - just keep in an email address to contact. I'm just not sure how to move it to github pages. Is that something you can help me with?

**Comment by eddiejaoude** [comment]
I will try to take a look tomorrow about moving it to **GitHub Pages**. 

Also, I created a ticket at the beginning of the year about the replacement for the contact for, thoughts? https://github.com/empowerhack/Hababy-Website/issues/3

**Comment by ahenkels** [comment]
Thanks @eddiejaoude! Doorbell.io is fine with me, otherwise just listing an email (rather than having a contact form) works. Thanks for the help.

**Comment by ahenkels** [comment]
@eddiejaoude I'm writing a short blog post on HaBaby for the Huffington Post - it would be really great if we could get at least something up (so the link doesn't appear broken on the main EmpowerHack page) by tomorrow.

**Comment by eddiejaoude** [comment]
@ahenkels there is an email address & telephone number on there, are they correct?

<img width="1222" alt="screenshot 2016-06-06 17 26 12" src="https://cloud.githubusercontent.com/assets/624760/15829504/fdf5bd02-2c0b-11e6-8630-8681c2737020.png">

Also, the social media links do not work, what are the values for these?

**Comment by ahenkels** [comment]
@eddiejaoude No, let's please use: 
email: hababy@empowerhack.com 
phone (if we need to include one): +44 782 110 2139
facebook: https://www.facebook.com/groups/548243475351886/
twitter: @HaBabyApp
Thank you so much!

**Comment by eddiejaoude** [comment]
Ok updated
